version: '3.8'

services:
  nextjs:
    image: shamimrana2006/nextjs-app:latest
    container_name: nextjs_app
    ports:
      - "5485:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network-frontend

  caddy:
    image: caddy:2-alpine
    container_name: caddy_server
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nextjs
    networks:
      - app-network-frontend

networks:
  app-network-frontend:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
