version: '3.8'

services:
  nextjs:
  # docker build -t shamimrana2006/frontend .
    image: shamimrana2006/frontend
    container_name: nextjs-app
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    # Uncomment if you need to add environment variables
    # env_file:
    #   - .env.production
    # Uncomment if you need volumes for development
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
